### ISSUE TITLE
The way to get total energy

### ISSUE THREAD

**Issue by WbSun723** [alex-l-m/tbmalt-qm9#1]
https://github.com/alex-l-m/tbmalt-qm9/blob/db9e36ae008cc927fd4a4b3dc169b0c66fe3be6d/tbmalt_run_individual.py#L120

Hi Alex, thank you very much for your repository.

I had a look of your example and I think you should use a different way to get total energy.
Like this:
`results = getattr(dftb_calculator, 'total_energy')`
 
What you get now from your way is actually `mermin_energy`. We will revise the code to avoid this issue.

**Comment by alex-l-m** [comment]
Fixed in 5f6714f6ace8451733ac6033cde1d87cc9f06151
